version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - '${APP_PORT:-8282}:8081'